name:                SpellCheckerService
version:             0.1.0.0
github:              "OmegaGreeNya/SpellCheckerService"
license:             BSD3
author:              "GreenCake (Nikolai)"
maintainer:          "megamancake@yandex.ru"
copyright:           "2022 GreenCake (Nikolai)"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/OmegaGreeNya/SpellCheckerService#readme>

default-extensions:
- RecordWildCards
- OverloadedStrings

dependencies:
- base >= 4.11 && <5
- aeson >= 2.0 && <2.2
- bytestring >=0.10 && < 0.12
- cheops-logger
- co-log-core
- co-log-json
- directory
- filepath
- http-client
- http-conduit
- servant-server
- text >=1.2 && < 2.1
- time
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  SpellCheckerService-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SpellCheckerService